//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public int Id_Imagen { get; set; }
        public int Id_Producto { get; set; }
        public string URL { get; set; }
        public bool Exportada { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
