//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionMvc2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
            this.Facturación = new HashSet<Facturación>();
        }
    
        public int Id_Factura { get; set; }
        public int Nombre { get; set; }
        public int Id_Cliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public int id_FormaPago { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Valor_Iva { get; set; }
        public decimal Valor_Descuento { get; set; }
        public decimal Neto { get; set; }
        public bool Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturación> Facturación { get; set; }
    }
}
